# Generated by Django 4.2.2 on 2023-06-20 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compra', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordencompra',
            name='id',
        ),
        migrations.RemoveField(
            model_name='presupuesto',
            name='id',
        ),
        migrations.RemoveField(
            model_name='presupuestoordencompra',
            name='id',
        ),
        migrations.AlterField(
            model_name='ordencompra',
            name='idOrden',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='presupuesto',
            name='idPresupuesto',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='presupuestoordencompra',
            name='idPresupuestoOrden',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
