# Generated by Django 4.2.2 on 2023-08-09 03:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('compra', '0003_presupuestoasociado_and_more'),
        ('inventario', '0002_ajustestock_ordenretiro_pedidoinsumo_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OrdenCompra',
        ),
        migrations.DeleteModel(
            name='PresupuestoOrdenCompra',
        ),
        migrations.AddField(
            model_name='presupuestoasociado',
            name='pedidoInsumo_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='inventario.pedidoinsumo'),
        ),
        migrations.AddField(
            model_name='presupuestoasociado',
            name='presupuesto_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='compra.presupuesto'),
        ),
    ]
