# Generated by Django 4.2.2 on 2023-08-17 00:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstadoHerramienta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now=True)),
                ('estado', models.CharField(choices=[('OK', 'OK'), ('En reparación', 'En reparación'), ('Mal estado', 'Mal estado')], default='OK', max_length=16)),
                ('observaciones', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.RenameField(
            model_name='ajustestock',
            old_name='insumo_id',
            new_name='insumo',
        ),
        migrations.RenameField(
            model_name='ajustestock',
            old_name='motivo',
            new_name='observaciones',
        ),
        migrations.RenameField(
            model_name='herramienta',
            old_name='tipoHerramienta_id',
            new_name='tipoHerramienta',
        ),
        migrations.RenameField(
            model_name='insumo',
            old_name='tipoInsumo_id',
            new_name='tipoInsumo',
        ),
        migrations.RenameField(
            model_name='ordenretiro',
            old_name='insumo_id',
            new_name='insumo',
        ),
        migrations.RenameField(
            model_name='ordenretiro',
            old_name='tarea_id',
            new_name='tarea',
        ),
        migrations.RemoveField(
            model_name='insumo',
            name='nombre',
        ),
        migrations.AddField(
            model_name='ajustestock',
            name='accionCantidad',
            field=models.CharField(choices=[('+', '+'), ('-', '-')], default='+', max_length=1),
        ),
        migrations.AddField(
            model_name='ajustestock',
            name='fecha',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='herramienta',
            name='fechaAlta',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='herramienta',
            name='observaciones',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='insumo',
            name='observaciones',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='insumo',
            name='puntoReposicion',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='herramienta',
            name='codigo',
            field=models.CharField(max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='insumo',
            name='codigo',
            field=models.CharField(max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='insumo',
            name='descripcion',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='tipoherramienta',
            name='descripcion',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='tipoinsumo',
            name='descripcion',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.DeleteModel(
            name='PedidoInsumo',
        ),
        migrations.AddField(
            model_name='estadoherramienta',
            name='herramienta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='inventario.herramienta'),
        ),
    ]
