# Generated by Django 4.2.2 on 2023-06-20 22:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OrdenCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idOrden', models.IntegerField(unique=True)),
                ('fecha', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Presupuesto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idPresupuesto', models.IntegerField(unique=True)),
                ('imagen', models.ImageField(upload_to='images/')),
                ('fecha', models.DateField()),
                ('proveedor', models.CharField(max_length=255)),
                ('total', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='PresupuestoOrdenCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idPresupuestoOrden', models.IntegerField(unique=True)),
                ('eleccion', models.BooleanField(default=False)),
                ('idOrden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='compra.ordencompra')),
                ('idPresupuesto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='compra.presupuesto')),
            ],
        ),
        migrations.AddField(
            model_name='ordencompra',
            name='idPresupuestoOrden',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='compra.presupuestoordencompra'),
        ),
    ]
