# Generated by Django 4.2.2 on 2023-08-09 01:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('compra', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordencompra',
            name='id',
        ),
        migrations.RemoveField(
            model_name='presupuesto',
            name='id',
        ),
        migrations.RemoveField(
            model_name='presupuesto',
            name='imagen',
        ),
        migrations.RemoveField(
            model_name='presupuestoordencompra',
            name='id',
        ),
        migrations.AlterField(
            model_name='ordencompra',
            name='idOrden',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='ordencompra',
            name='idPresupuestoOrden',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='compra.presupuestoordencompra'),
        ),
        migrations.AlterField(
            model_name='presupuesto',
            name='idPresupuesto',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='presupuestoordencompra',
            name='idOrden',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='compra.ordencompra'),
        ),
        migrations.AlterField(
            model_name='presupuestoordencompra',
            name='idPresupuesto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='compra.presupuesto'),
        ),
        migrations.AlterField(
            model_name='presupuestoordencompra',
            name='idPresupuestoOrden',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
